paths:
  build:
    main: './dist'
    pages: './dist'
    javascript: './dist/assets/js'
    images: './dist/assets/images'
    css: './dist/assets/css'
    assets: './dist/assets'
  source:
    main: './src'
    pages: './src/pages/**/*.html'
    javascript: './src/js/{main,main-admin}.{js,ts}'
    images: './src/assets/images/**/*'
    scss: './src/scss/{main,main-admin}.scss'
    assets:
      - './src/assets/**/*'
      - '!./src/assets/{images}/**/*'
  watcher:
      pages: './src/pages/**/*.html'
      pagesComponents: './src/{layouts,partials}/**/*.html'
      pagesData: './src/data/**/*.{js,json,yml}'
      javascript: './src/js/**/*.{js,ts}'
      images: './src/assets/images/**/*'
      scss: './src/scss/**/*.scss'
      assets:
      - './src/assets/**/*'
      - '!./src/assets/{images}/**/*'
  scssDependencies:
    - 'node_modules/bootstrap/scss'
    - 'node_modules/reset-css/sass'
modules:
  panini:
    root: "./src/pages/"
    layouts: "./src/layouts/"
    partials: "./src/partials/"
    data: "./src/data/"
    helpers: "./src/helpers/"
  postCss:
    - 'last 2 versions'
    - 'ie >= 9'
    - 'ios >= 7'
server:
  contentBase: './dist'
  port: 8080
