paths:
  build:
    main: './build'
    pages: './build'
    javascript: './build/assets/js'
    images: './build/assets/images'
    css: './build/assets/css'
    assets: './build/assets'
  source:
    main: './src'
    pages: './src/pages/**/*.html'
    javascript: './src/js/{main,main-admin}.{js,ts}'
    images: './src/assets/images/**/*'
    scss: './src/scss/{main,main-admin}.scss'
    github:
      main: ./src/github
      cname: ./src/github/CNAME
    assets:
      - './src/assets/**/*'
      - '!./src/assets/{images}/**/*'
  watcher:
      pages: './src/pages/**/*.html'
      pagesComponents: './src/{layouts,partials}/**/*.html'
      pagesData: './src/data/**/*.{js,json,yml}'
      javascript: './src/js/**/*.{js,ts}'
      images: './src/assets/images/**/*'
      scss: './src/scss/**/*.scss'
      assets:
      - './src/assets/**/*'
      - '!./src/assets/{images}/**/*'
  scssDependencies:
    - 'node_modules/bootstrap/scss'
    - 'node_modules/reset-css/sass'
modules:
  panini:
    root: "./src/pages/"
    layouts: "./src/layouts/"
    partials: "./src/partials/"
    data: "./src/data/"
    helpers: "./src/helpers/"
server:
  contentBase: './build'
  port: 8080
